---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
lint: |
  set -e
  ansible-lint
driver:
  name: podman
platforms:
  # service-enabled Docker image by geerlingguy
  - name: podman-instance-${TOX_ENVNAME}-${MOLECULE_DISTRO:-debian10}
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian10}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  options:
    v: true
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks, timer, yaml
      stdout_callback: yaml
verifier:
  name: ansible
