---
name: create declared labels

"on":
  issues:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/issue-label-manager.yml"
      - ".github/labels.yml"

jobs:
  labels:
    name: Invoke issue-label-manager action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: crazy-max/ghaction-github-labeler@77450f9fa47c41fbab15c0923417fff00730ffa3 # tag=v4
        if: success()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false # false -> delete labels that aren't in `yaml-file`
