name: Close Issues with no timely response from Author

# Both `issue_comment` and `scheduled` event types are required for this Action
# to work properly.
on:
  issue_comment:
    types: [created]
  schedule:
    # "At 00:00"
    - cron: '0 0 * * *'

jobs:
  noResponse:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          responseRequiredLabel: 'question'  # standard label created by github ;)
          token: ${{ github.token }}